#!/usr/bin/env bash
set -e

REMOTE=eldridgejm.github.io

repodir=$(pwd)

# create a temporary directory
tmpdir=$(mktemp --directory)

if [[ ! "$tmpdir" || ! -d "$tmpdir" ]]; then
  echo "Could not create temp dir"
  exit 1
fi

function cleanup {
    rm -rf $tmpdir
}

trap cleanup EXIT

# export the artifacts from this repo to the temporary directory
# mkdir $tmpdir/
cp -r build/* $tmpdir/
echo "Published to $tmpdir/"

# clone the public
cd $tmpdir
git clone -b gh-pages ssh://git@github.com/eldridgejm/$REMOTE

# synchronize the remote with the expanded artifacts
cd $REMOTE/ && rm -rf *
cd ..
cp -r exported/* $REMOTE

# publish them
cd $REMOTE 
git add .
git commit -a -m "Machine user push." | :
git push origin gh-pages
